version: '2'

services:
  app:
    build: 
      dockerfile: Dockerfile
    image: server
    container_name: server
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - '80:80'
      - '443:443'
    networks:
      - 'app-networks'

  db: 
    image: mysql:8.3
    container_name: db
    volumes: 
      - dbdata:/var/lib/mysql/
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - 'app-networks'

networks:
  app-networks:
    driver: bridge

volumes:
  dbdata:
    driver: local